export const metadata = {
  title: "CMS",
  description: "Generated by create next app",
};

export default async function DasboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
