export const metadata = {
  title: "CMS",
  description: "Generated by create next app",
};

import Sidebar from "../components/Sidebar";

export default async function DasboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full max-h-screen">
      <Sidebar orgName="Rely Edu CMS" title="Dashboard" />
      {children}
    </div>
  );
}
